#ifndef BACKGAMMON_LOGIC_H
#define BACKGAMMON_LOGIC_H

/* Generated with cbindgen:0.6.1 */

/*
 * WARNING:
 * This file is autogenerated by `cbindgen`. Don't modify this manually.
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>

#define PLAYER_BLACK 0

#define PLAYER_WHITE 1

typedef enum {
    Black,
    White,
} RustPlayer;

typedef uint8_t Die;

typedef struct {
    Die d1;
    Die d2;
} RustDice;

#endif /* BACKGAMMON_LOGIC_H */
