#ifndef BACKGAMMON_LOGIC_H
#define BACKGAMMON_LOGIC_H

/* Generated with cbindgen:0.6.1 */

/*
 * WARNING:
 * This file is autogenerated by `cbindgen`. Don't modify this manually.
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>

#define PLAYER_BLACK 0
#define PLAYER_WHITE 1
#define BOARD_SIZE 24

typedef enum {
    Black,
    White,
} RustPlayer;

typedef uint8_t Die;

typedef struct {
    Die d1;
    Die d2;
} RustDice;

typedef struct {
    RustPlayer owner;
    uint8_t count;
} RustPoint;

typedef RustPoint *RustMaybePoint;

typedef RustMaybePoint **RustInternalBoard;

RustMaybePoint init_some_point(void);
RustMaybePoint init_none_point(void);
RustPlayer *init_player(void);
RustPoint *init_point(void);
//RustInternalBoard init_internal_board(void);
uint8_t init_internal_board(void);

#endif /* BACKGAMMON_LOGIC_H */
