name:                backgammon-server
version:             0.1.0.0
github:              "ehegnes/backgammon-server"
license:             GPL-3.0
author:              "Eric Hegnes <eric.hegnes@gmail.com>, Charly Resendiz <cbresendiz1@gmail.com"
maintainer:          "Eric Hegnes <eric.hegnes@gmail.com>"
copyright:           "2018 Eric Hegnes, Charly Resendiz"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/ehegnes/backgammon-server#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:      src
  other-extensions: ForeignFunctionInterface
  build-tools:      c2hs
  cc-options:       -D_BITS_FLOATN_H
  extra-libraries:  backgammon_logic

executables:
  backgammon-server-exe:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -g
    - -dcore-lint
    - -debug
    dependencies:
    - backgammon-server

tests:
  backgammon-server-test:
    main:             Spec.hs
    source-dirs:      test
    other-extensions: ForeignFunctionInterface
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backgammon-server
    - hspec
