name:                backgammon-server
version:             0.1.0.0
github:              "ehegnes/backgammon-server"
license:             GPL-3.0
author:              "Eric Hegnes"
maintainer:          "eric.hegnes@gmail.com"
copyright:           "2018 Eric Hegnes"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ehegnes/backgammon-server#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  backgammon-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backgammon-server
    default-extensions:  ForeignFunctionInterface
    extra-lib-dirs:      ../backgammon-logic/target/debug
    extra-libraries:     backgammon_logic

tests:
  backgammon-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backgammon-server
